### ISSUE TITLE
RSS Feeds seems empty?

### ISSUE THREAD

**Issue by benjaminchait** [robotbill/webring#4]
https://robot-friend-ring.netlify.app/feeds.xml which is on the top page of 
<img width="143" alt="image" src="https://user-images.githubusercontent.com/3802865/156894254-c5076301-431e-44da-8559-0390a27e9733.png">

...does not seem to populate with any RSS content. Is that expected? (I don't know enough about this project, but feels like something might be amiss...)

**Comment by robotbill** [comment]
This is one of the parts of the original project that I didn't touch or test. The feeds XML looks like:
```xml
<?xml version="[1.0]()" encoding="UTF-8"?>
<opml version="1.0">
    <head>
        <title>Robot Friends Member Feeds</title>
    </head>
    <body>     
        <outline type="[rss]()" text="[Locker785]()" title="[Locker785]()" xmlUrl="[https://locker785.com/feed/feed.xml]()" htmlUrl="[https://locker785.com]()" />
        <outline type="[rss]()" text="[Evan&#39;s Blorg]()" title="[Evan&#39;s Blorg]()" xmlUrl="[https://evanstoner.com/atom.xml]()" htmlUrl="[https://evanstoner.com]()" />
        <outline type="[rss]()" text="[Benjamin Chait]()" title="[Benjamin Chait]()" xmlUrl="[https://benjaminchait.net/feed.xml]()" htmlUrl="[https://benjaminchait.net]()" />
    </body>
</opml>
```

So, like it does have all of our feeds aggregated in it.  It appears to be the [https://en.wikipedia.org/wiki/OPML](OPML) format which lets you list multiple feeds.  Reeder doesn't seem to like it. But Feedly has [a way to import OPML files](https://blog.feedly.com/opml/). However, that doesn't seem like it's intended to hook up to a URL.

I wonder if I should just get rid of it.

**Comment by benjaminchait** [comment]
Oh fascinating. I only opened it in Safari, which showed what looked like an empty page (with the title `Robot Friends Member Feeds` showing) so I thought something was broken:
![IMG_0734](https://user-images.githubusercontent.com/3802865/156897465-8847cbc5-5d5a-4926-b20a-ab73b0737559.png)

But viewing source, I do see the OPML (though admittedly, I’ve never really played with these kinds of files).

× 

I don’t have a strong opinion on whether it stays or is removed, though I tend to lean on removing it for simplicity. I suppose you could also rename it to “OPML of all member RSS feeds” or something, too. But, I’ll leave that to you and will close this comment as _I was wrong_ — that link is correctly populating!

Also, 🙏 thanks for responding and helping me see what I’d missed the first time!
